[tool.pyright]
typeCheckingMode = "standard"
include = ["app"]
exclude = ["**/__pycache__", "venv", ".venv"]
pythonVersion = "3.11"

[tool.ruff]
line-length = 88
target-version = "py311"
fix = true
unsafe-fixes = true
extend-exclude = ["__pycache__", "migrations"]

select = ["E", "F", "B", "I", "UP", "N"]
ignore = ["E501"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"