"""create admin user

Revision ID: b9760552fbe1
Revises: b237408d20ee
Create Date: 2025-08-21 03:53:22.134272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9760552fbe1'
down_revision: Union[str, Sequence[str], None] = 'b237408d20ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        sa.text(
            """
            INSERT INTO users (name, email, role, password)
            VALUES (:name, :email, :role, :password)
            """
        ).bindparams(
            name="admin",
            email="admin@example.com",
            role="admin",
            password="$2b$12$3PQH4VXbJ1eJhSDruzQJo.rPHvVZeUax3UUxpJvTeTNUeRjbLFNhG",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
