"""change user id

Revision ID: e955599b4dde
Revises: 98bdd774e9ad
Create Date: 2025-08-21 03:51:36.535832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e955599b4dde'
down_revision: Union[str, Sequence[str], None] = '98bdd774e9ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.drop_column('users', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_column('users', 'user_id')
    # ### end Alembic commands ###
